## ----------------------------------------------------------------------------
## nexus | DEMO_muons.init.mac
##
## Initialization macro to simulate muons in the NEXT-DEMO detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/execute macros/physics/DefaultPhysicsList.mac

/nexus/RegisterGeometry NDGArChamber #CylindricChamber #Next1EL

/nexus/RegisterGenerator ScintillationGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterTrackingAction OpticalTrackingAction
#/nexus/RegisterEventAction SaveAllEventAction
/nexus/RegisterRunAction DefaultRunAction

/nexus/RegisterMacro macros/DEMO_photons.config.mac

